POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "First blog",
  "author": "HA",
  "url": "www/jsjsj",
  "likes": 1
}

###
GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json