POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhaHZlbiIsImlkIjoiNjNjMWI4NTgwM2JjZWRlMzMzZTE5MzU4IiwiaWF0IjoxNjc0ODM5OTU1fQ.LKo2P7pxjzuhyOInEDeMjEVYxyJYupUAL6aVEEBovdc

{
  "title": "heininBlogi",
  "author": "HA",
  "url": "www/jsfkf",
  "likes": 4
}

###
GET http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
###
DELETE http://localhost:3001/api/blogs/63c1aaf08bbecf4541123c96 HTTP/1.1
###
PUT http://localhost:3001/api/blogs/62d70745f3d133697762ce38 HTTP/1.1
content-type: application/json

{
  "title": "dingdong",
  "author": "HA",
  "url": "www/jsfkf",
  "likes": 6,
  "userId":"63c1b85803bcede333e19358"
}
###
GET http://localhost:3001/api/users HTTP/1.1
content-type: application/json
###
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
  "username": "käpy2",
  "name": "KA",
  "password": "salainenKäpy"
}
###

POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
  "username": "hahven",
  "password": "salasana"
}


